name : subway frontend workflow

on:
  push:
    branches : 
    - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://my-subway-recipes.site
